In [1]:
import pandas as pd
import numpy as np
import io
import requests
from datetime import datetime

In [2]:
url = 'https://phl.carto.com/api/v2/sql?q=SELECT+*,+ST_Y(the_geom)+AS+lat,+ST_X(the_geom)+AS+lng+FROM+opa_properties_public&filename=opa_properties_public&format=csv&skipfields=cartodb_id,the_geom,the_geom_webmercator'
df = pd.read_csv(url)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3050: DtypeWarning: Columns (1,3,10,28,29,30,31,32,33,70) have mixed types. Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
### new columns
added_columns = [
    '# UNITS',
    'REIS Submarket',
    'CITY',
    'STATE',
    'RESI',
    'CONDO',
    'UNIT',
    'COMM',
    'TOT ASSD $',
    'RE TAXES',
]

### OVERWRITE instructions for the original data file
### these instructions could be manually altered  
rename_dict = {
    'number_of_rooms': {
        'delete': 0,
        'new_name': '# ROOMS',
    },
    'assessment_date': {
        'delete': 0,
        'new_name': 'assessment_date',
    },
    'beginning_point': {
        'delete': 1,
    },
    'book_and_page': {
        'delete': 1,
    },
    'building_code': {
        'delete': 1,
    },
    'building_code_description': {
        'delete': 0,
        'new_name': 'BLDG CODE',
    },
    'category_code': {
        'delete': 1,
    },
    'category_code_description': {
        'delete': 0,
        'new_name': 'BLDG CAT',
    },
    'census_tract': {
        'delete': 1,
    },
    'central_air': {
        'delete': 0,
        'new_name': 'CENTRAL AIR',
    },
    'cross_reference': {
        'delete': 1,
    },
    'date_exterior_condition': {
        'delete': 0,
        'new_name': 'EXT CONDITION DATE',
    },
    'depth': {
        'delete': 0,
        'new_name': 'LOT DEPTH',
    },
    'exempt_building': {
        'delete': 0,
        'new_name': 'BLDG EXEMPT',
    },
    'exempt_land': {
        'delete': 0,
        'new_name': 'LAND EXEMPT',
    },
    'exterior_condition': {
        'delete': 0,
        'new_name': 'EXT CONDITION',
    },
    'fireplaces': {
        'delete': 0,
        'new_name': '# FIREPLACE',
    },
    'frontage': {
        'delete': 0,
        'new_name': 'LOT FRONTAGE',
    },
    'fuel': {
        'delete': 1,
    },
    'garage_spaces': {
        'delete': 0,
        'new_name': 'GARAGE',
    },
    'garage_type': {
        'delete': 0,
        'new_name': 'GARAGE TYPE',
    },
    'general_construction': {
        'delete': 1,
    },
    'geographic_ward': {
        'delete': 1,
    },
    'homestead_exemption': {
        'delete': 0,
        'new_name': 'homestead_exemption',
    },
    'house_extension': {
        'delete': 1,
    },
    'house_number': {
        'delete': 1,
    },
    'interior_condition': {
        'delete': 0,
        'new_name': 'INT CONDITION',
    },
    'location': {
        'delete': 0,
        'new_name': 'ADDRESS',
    },
    'mailing_address_1': {
        'delete': 1,
    },
    'mailing_address_2': {
        'delete': 1,
    },
    'mailing_care_of': {
        'delete': 1,
    },
    'mailing_city_state': {
        'delete': 0,
        'new_name': 'OWNER CITY',
    },
    'mailing_street': {
        'delete': 0,
        'new_name': 'OWNER ADDRESS',
    },
    'mailing_zip': {
        'delete': 0,
        'new_name': 'OWNER ZIP',
    },
    'market_value': {
        'delete': 0,
        'new_name': 'MARKET VALUE',
    },
    'market_value_date': {
        'delete': 1,
    },
    'number_of_bathrooms': {
        'delete': 0,
        'new_name': '# BATH',
    },
    'number_of_bedrooms': {
        'delete': 0,
        'new_name': '# BED',
    },
    'basements': {
        'delete': 0,
        'new_name': 'BASEMENT',
    },
    'number_stories': {
        'delete': 0,
        'new_name': '# FLOORS',
    },
    'off_street_open': {
        'delete': 0,
        'new_name': 'off_street_open'
    },
    'other_building': {
        'delete': 0,
        'new_name': 'BUILDING',
    },
    'owner_1': {
        'delete': 0,
        'new_name': 'OWNER',
    },
    'owner_2': {
        'delete': 1,
    },
    'parcel_number': {
        'delete': 0,
        'new_name': 'PARCEL ID',
    },
    'parcel_shape': {
        'delete': 0,
        'new_name': 'PARCEL SHAPE',
    },
    'quality_grade': {
        'delete': 1
    },
    'recording_date': {
        'delete': 0,
        'new_name': 'RECORDING DATE',
    },
    'registry_number': {
        'delete': 1
    },
    'sale_date': {
        'delete': 0,
        'new_name': 'SALE DATE',
    },
    'sale_price': {
        'delete': 0,
        'new_name': 'SALE PRICE',
    },
    'separate_utilities': {
        'delete': 1,
    },
    'sewer': {
        'delete': 1,
    },
    'site_type': {
        'delete': 1,
    },
    'state_code': {
        'delete': 1,
    },
    'street_code': {
        'delete': 1,
    },
    'street_designation': {
        'delete': 1,
    },
    'street_direction': {
        'delete': 1,
    },
    'street_name': {
        'delete': 1,
    },
    'suffix': {
        'delete': 1,
    },
    'taxable_building': {
        'delete': 0,
        'new_name': 'BLDG ASSD $',
    },
    'taxable_land': {
        'delete': 0,
        'new_name': 'LAND ASSD $',
    },
    'topography': {
        'delete': 0,
        'new_name': 'TOPOGRAPHY',
    },
    'total_area': {
        'delete': 0,
        'new_name': 'LAND SF',
    },
    'total_livable_area': {
        'delete': 0,
        'new_name': 'GSF',
    },
    'type_heater': {
        'delete': 1,
    },
    'unfinished': {
        'delete': 1,
    },
    'unit': {
        'delete': 0,
        'new_name': 'UNIT #',
    },
    'utility': {
        'delete': 1,
    },
    'view_type': {
        'delete': 0,
        'new_name': 'VIEW',
    },
    'year_built': {
        'delete': 0,
        'new_name': 'YEAR BUILT',
    },
    'year_built_estimate': {
        'delete': 1,
    },
    'zip_code': {
        'delete': 0,
        'new_name': 'ZIP',
    },
    'zoning': {
        'delete': 0,
        'new_name': 'ZONING',
    },
    'objectid': {
        'delete': 1,
    },
    'lat': {
        'delete': 0,
        'new_name': 'LATITUDE',
    },
    'lng': {
        'delete': 0,
        'new_name': 'LONGITUDE',
    },
}

instructions = {
    'added_columns': added_columns,
    'rename_dict': rename_dict,
}

In [131]:
def pre_clean_df(df, instructions):
    added_columns = instructions['added_columns']
    rename_dict = instructions['rename_dict']
    orig_columns = list(instructions['rename_dict'].keys())
    df_new = df.copy()[orig_columns]
    
    for column in orig_columns:
        if rename_dict[column]['delete'] == 1:
            df_new = df_new.drop([column], axis=1)
        if rename_dict[column]['delete'] == 0:
            df_new = df_new.rename(columns={column: rename_dict[column]['new_name']})
    
    df_new = df_new.reindex(df_new.columns.tolist()+added_columns, axis=1)\
                   .astype(dtype={'SALE DATE': str})
    
    df_new['SALE DATE'] = pd.to_datetime(df_new['SALE DATE'], errors='coerce')
    df_new = df_new.sort_values(by=['SALE DATE'], ascending=False)\
                   .drop(df_new[df_new['SALE DATE']==pd.NaT].index)\
                   .reset_index(drop=True)
    
    return df_new

def subset_df_date(df_new, deltadays):
    delta = pd.Timedelta(deltadays)
    df_new = df_new.sort_values(by=['SALE DATE'], ascending=False)
    latest_date = df_new['SALE DATE'].iloc[0]
    earliest_date = latest_date-delta
    keep_index = df_new[(df_new['SALE DATE']>=earliest_date) & 
                        (df_new['SALE DATE']<=latest_date)].index
    df_sub = df_new.iloc[keep_index]\
                   .reset_index(drop=True)
    return df_sub

def update_PLUTO(pluto, df_sub):
        pluto_addresses = pluto['ADDRESS'].tolist()
        sub_addresses = df_sub['ADDRESS'].tolist()
        pluto_update = pluto.copy()
        df_added = pd.DataFrame(columns=pluto.columns)
            
        ### loop through all the addresses in the new data 
        ### to match the addresses in the PLUTO dataset 
        for address in sub_addresses:
            if address in pluto_addresses:
                added = df_sub[df_sub['ADDRESS']==address]['PARCEL ID']\
                            .values.tolist()
                original = pluto[pluto['ADDRESS']==address]['PARCEL ID']\
                            .values.tolist()
                print(added)
                # address in the PLUTO whose data need to be updated 
                if set(added) == set(original):
                    pluto_update.at[
                        pluto_update[pluto_update['ADDRESS']==address].index,
                        ['GSF', 'SALE PRICE', 'SALE DATE']
                    ] = df_sub[df_sub['ADDRESS']==address][['GSF', 'SALE PRICE', 'SALE DATE']]\
                          .values\
                          .tolist()
                else:
                    commons = set(added).intersection(set(original))
                    diffs = set(added) - set(original)
                    
                    for pid in list(commons):
                        pluto_update.at[
                            pluto_update[(pluto_update['ADDRESS']==address) & 
                                         (pluto_update['PARCEL ID']==pid)].index,
                            ['GSF', 'SALE PRICE', 'SALE DATE']
                        ] = df_sub[(df_sub['ADDRESS']==address) & 
                                   (df_sub['PARCEL ID']==pid)][['GSF', 'SALE PRICE', 'SALE DATE']]\
                                  .values\
                                  .tolist()
                    
                    if not diffs:
                        # to account for the addresses that have multiple properties
                        added_rows = df_sub.loc[(df_sub['ADDRESS']==address) &
                                                (df_sub['PARCEL ID'].isin(list(diffs)))]
                        for i in range(added_rows.shape[0]):
                            df_added = df_added.append(added_rows.iloc[i], 
                                                       ignore_index=True)
            else:
                added_row = df_sub.loc[df_sub['ADDRESS']==address]
                df_added = df_added.append(added_row, ignore_index=True)
        
        df_added = df_added[pluto_update.columns]
        pluto_final = pd.concat([pluto_update, df_added],
                                ignore_index=True)\
                        .sort_values(by='SALE DATE',
                                     ascending=False)\
                        .drop_duplicates(subset='PARCEL ID',
                                         keep='first')\
                        .reset_index(drop=True)
        
        return pluto_final

In [94]:
df_new = pre_clean_df(df, instructions)
df_sub = subset_df_date(df_new, '40 days')

In [95]:
pluto = pd.read_csv('../data/project/PHLPL-001 All_Properties [byaddress;location] PLUTO.csv')

In [96]:
pluto['SALE DATE'] = pd.to_datetime(pluto['SALE DATE'], errors='coerce')

In [97]:
pluto = pluto.sort_values(by=['SALE DATE'], ascending=False)

In [132]:
pluto_update1 = update_PLUTO(pluto, df_sub)

[162293500]
[311238800]
[453010600]
[395330900]
[591144000]
[888115116]
{888115116}
[342266400]
[261355900]
[551500200]
[393142800]
[371201100]
[542399600]
[252245000]
[491043100]
[171304900]
[663282000]
[542072600]
[261124800]
[432153300]
[871563890]
[593116700]
[331226800]
[71232500]
[421200800]
[541265500]
[491047700]
[513190000]
[282133900]
[273050200]
[252074900]
[871581770]
[261374900]
[631263000]
[71549200]
[303001500]
[551134800]
[392141100]
[561484800]
[21042400]
[551317400]
[541275800]
[331343700]
[662184000]
[251372400]
[364090100]
[663110800]
[331232000]
[621275100]
[365169500]
[311166500]
[395204700]
[592282015]
[292244400]
[562313716]
[411217900]
[551192100]
[282014400]
[492160400]
[394418500]
[132204700]
[343341500]
[502390900]
[132157500]
[252237000]
[57123121]
[513006300]
[332465500]
[122185000]
[541044300]
[272041500]
[21190100]
[492098400]
[252234700]
[542395000]
[871582790]
[251474500]
[342249900]
[521098700]
[252087700]
[365249000]
[364397300]
[422368600]
[371062400]
[233124005]
[181181700]
[232028500]
[212344900]
[663398500]
[261137000]
[453347500]
[542211000]
[372009600]
[403027300]
[412308800]
[252161700]
[522234800]
[213206900]
[41307300]
[593188900]
[561463900]
[331415200]
[342348600]
[32109000]
[552469600]
[662458100]
[663102400]
[171239300]
[232179600]
[641063500]
[171310500]
[122048800]
[433070300]
[571139700]
[361284700]
[211161800]
[102241800]
[365225600]
[511101700]
[212153100]
[642201600]
[881217110]
[232178900]
[331280800]
[201088750]
[233058300]
[501040500]
[441206000]
[101282600]
[402008400]
[601049500]
[551193500]
[381071100]
[211447100]
[542183200]
[662560400]
[132122100]
[181064400]
[881009100]
[133030800]
[482238900]
[561331300]
[441296500]
[12187600]
[342062400]
[411346600]
[152337900]
[502433600]
[261151800]
[42001600]
[662023800]
[541134600]
[365082400]
[361141100]
[451328800]
[421070200]
[162163200]
[332247600]
[491080100]
[502348600]
[391096000]
[888650066]
set()
[888080347]
set()
[214222100]
[492030300]
[422043200]
[471093110]
[42024400]
[302303800]
[234159500]
[881504200]
[888035894, 888035896, 888035892]
{888035892}
[603055400]
[663163400]
[888093734, 888093724]
set()
[881506700]
[133092100]
[621226000]
[592020500]
[522138800]
[881577900]
[571031000]
[91112600]
[211332500]
[261028100]
[322193400]
[381330300]
[631298100]
[112000725]
[531180800]
[888035894, 888035896, 888035892]
{888035892}
[332389000]
[421513100]
[411211305]
[521310700]
[213255900]
[542301000]
[604130800]
[212397810]
[621510600]
[102161900]
[888035894, 888035896, 888035892]
{888035892}
[531080900]
[21065410]
[621477900]
[542020500]
[241046300]
[83025800]
[182198200]
[442316100]
[888181498]
set()
[273102300]
[604106400]
[393035700]
[511196500]
[102172700]
[641063600]
[412432800]
[81011110]
[421597200]
[232139500]
[652010900]
[61229500]
[12278200]
[572040000]
[502483800]
[572074100]
[291345900]
[571043800]
[652151700]
[211491100]
[341102900]
[12228300]
[632112700]
[12228700]
[888310404]
set()
[582156200]
[353303200]
[12080700]
[41085600]
[542203800]
[412382000]
[641024800]
[122202100]
[34070700]
[663244500]
[514000400]
[372253600]
[482359200]
[313224000]
[521012800]
[171238100]
[642324400]
[441147100]
[344373800]
[631095700]
[152130200]
[482170500]
[432011500]
[364151300]
[888030590]
set()
[551401300]
[421239600]
[888630372]
set()
[591216700]
[421578300]
[71330600]
[222066600]
[602166600]
[462005100]
[512052500]
[151315000]
[11251500]
[641178600]
[591223800]
[888022488]
set()
[571262400]
[403138700]
[151382410]
[582521703]
set()
[888115316]
set()
[522041000]
[262122100]
[381096200]
[92003000]
[382128570]
[252323100]
[551161300]
[612164600]
[888094664, 888094508]
set()
[292243010]
[662160200]
[72184600]
[491488500]
[102160900]
[652224500]
[592307200]
[213178723]
[581275000]
[12498000]
[592108600]
[21539400]
[171147100]
[621001300]
[888093734, 888093724]
set()
[491322400]
[123089700]
[41265500]
[451309800]
[262288400]
[221246000]
[213248400]
[871245900]
[871563860]
[171020200]
[421382600]
[21618000]
[11128900]
[291345800]
[406266600]
[351129900]
[651147700]
[401176300]
[601065000]
[391320400]
[21607500]
[261329200]
[551238900]
[642066500]
[102168800]
[888084315, 888084353]
{888084353}
[341179200]
[888650170]
set()
[442206300]
[371251500]
[391037300]
[582094300]
[212194400]
[663177300]
[482354700]
[888084315, 888084353]
{888084353}
[631342200]
[172064100]
[482313300]
[81118900]
[242146005]
[572001804]
[312158000]
[302129100]
[72192400]
[292134800]
[621262300]
[92007200]
[365338100]
[394206900]
[406302000]
[641154300]
[212381470]
[223028900]
[214165300]
[542159600]
[888580915]
set()
[301299000]
[162044000]
[364423400]
[394317800]
[551160400]
[381064700]
[252515900]
[663442500]
[406620700]
[193244400]
[234132300]
[102037700]
[662258521]
[252449500]
[102099600]
[262180900]
[888380154]
[211424010]
[262009000]
[41336200]
[888072750]
set()
[453424300]
[202191800]
[361125600]
[111246000]
[382225800]
[551197100]
[331052400]
[542470900]
[601062400]
[641183000]
[22191600]
[532200400]
[342173300]
[451165600]
[181434800]
[32134101]
[291117300]
[562176000]
[621493100]
[482373100]
[461229700]
[352103600]
[642184600]
[622367100]
[101363100]
[323190200]
[421028000]
[291380500]
[513179110]
[604203700]
[522041100]
[562141900]
[363133400]
[562008800]
[888050937]
set()
[404101600]
[511155000]
[888210576]
set()
[261359900]
[532262800]
[406018300]
[282113300]
[442257200]
[122199100]
[406194300]
[888093474]
set()
[251431600]
[61261800]
[453320900]
[323003200]
[252017100]
[622220000]
[552442600]
[181205020]
[621355600]
[382187500]
[572101100]
[262372600]
[888085285]
set()
[513254500]
[172489900]
[521402500]
[432340200]
[364397900]
[292248000]
[651211200]
[592272000]
[322165500]
[242119400]
[412026800]
[394128300]
[888151015, 888150631]
set()
[572094623]
[313068000]
[663157200]
set()
[343374400]

KeyboardInterrupt:

In [119]:
pluto_update1

,ADDRESS,REIS Submarket,CITY,STATE,ZIP,PARCEL ID,UNIT #,LATITUDE,LONGITUDE,YEAR BUILT,...,BLDG ASSD $,LAND ASSD $,TOT ASSD $,RE TAXES,TOPOGRAPHY,VIEW,ZONING,RECORDING DATE,homestead_exemption,off_street_open
0,1903 N PHILIP ST,North Frankford,Philadelphia,PA,19122,183286100,NaN,39.979368,-75.137918,1920,...,36120.0,32280.0,68400.0,948,F,I,RM1,6/10/2019,39200.0,0.0
1,1839-47 BLAIR ST,North Frankford,Philadelphia,PA,19125,888181568,7,39.978068,-75.131378,2017,...,80767.0,42700.0,123467.0,"1,711",F,I,CMX2,6/7/2019,0.0,0.0
2,1252 PALETHORP ST,North Frankford,Philadelphia,PA,19122,888181894,1,39.970801,-75.138852,2018,...,355300.0,62700.0,418000.0,"5,793",F,I,RM1,6/10/2019,NaN,0.0
3,620 N 03RD ST,Center City,Philadelphia,PA,19123,888501304,000002C,39.962035,-75.143448,2017,...,488400.0,79500.0,567900.0,"7,870",F,I,NaN,6/3/2019,0.0,0.0
4,4916 KNORR ST,North Frankford,Philadelphia,PA,19135,412016300,NaN,40.022896,-75.042486,1920,...,80862.0,19338.0,100200.0,"1,389",F,I,RSA5,6/4/2019,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488597,1700 S 20TH ST,NaN,NaN,NaN,191452003,871168550,NaN,39.930421,-75.178428,1920,...,121200.0,30300.0,NaN,NaN,F,I,CMX1,2019-11-25,NaN,0.0
488598,2135 WALNUT ST,NaN,NaN,NaN,191034404,888082482,0000102,39.951128,-75.177119,1900,...,251730.0,27970.0,NaN,NaN,NaN,A,CMX4,2019-11-21,NaN,0.0
488599,7627-31 GERMANTOWN AVE,NaN,NaN,NaN,191183523,871514550,NaN,40.066461,-75.195962,1845,...,218880.0,54720.0,NaN,NaN,F,I,SPPOA,2019-11-20,NaN,10.0
488600,1862 N 27TH ST,NaN,NaN,NaN,191212600,323173400,NaN,39.984365,-75.178421,0,...,0.0,5700.0,NaN,NaN,F,NaN,RSA5,2019-11-22,NaN,0.0
488601,628 SPRING LN,NaN,NaN,NaN,191281046,212408912,NaN,40.067447,-75.245553,1950,...,250750.0,44250.0,NaN,NaN,A,C,RSD3,2019-11-29,NaN,0.0

In [124]:
pluto_update1.drop_duplicates(subset='PARCEL ID', keep='first')

,ADDRESS,REIS Submarket,CITY,STATE,ZIP,PARCEL ID,UNIT #,LATITUDE,LONGITUDE,YEAR BUILT,...,BLDG ASSD $,LAND ASSD $,TOT ASSD $,RE TAXES,TOPOGRAPHY,VIEW,ZONING,RECORDING DATE,homestead_exemption,off_street_open
0,1903 N PHILIP ST,North Frankford,Philadelphia,PA,19122,183286100,NaN,39.979368,-75.137918,1920,...,36120.0,32280.0,68400.0,948,F,I,RM1,6/10/2019,39200.0,0.0
1,1839-47 BLAIR ST,North Frankford,Philadelphia,PA,19125,888181568,7,39.978068,-75.131378,2017,...,80767.0,42700.0,123467.0,"1,711",F,I,CMX2,6/7/2019,0.0,0.0
2,1252 PALETHORP ST,North Frankford,Philadelphia,PA,19122,888181894,1,39.970801,-75.138852,2018,...,355300.0,62700.0,418000.0,"5,793",F,I,RM1,6/10/2019,NaN,0.0
3,620 N 03RD ST,Center City,Philadelphia,PA,19123,888501304,000002C,39.962035,-75.143448,2017,...,488400.0,79500.0,567900.0,"7,870",F,I,NaN,6/3/2019,0.0,0.0
4,4916 KNORR ST,North Frankford,Philadelphia,PA,19135,412016300,NaN,40.022896,-75.042486,1920,...,80862.0,19338.0,100200.0,"1,389",F,I,RSA5,6/4/2019,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488597,1700 S 20TH ST,NaN,NaN,NaN,191452003,871168550,NaN,39.930421,-75.178428,1920,...,121200.0,30300.0,NaN,NaN,F,I,CMX1,2019-11-25,NaN,0.0
488598,2135 WALNUT ST,NaN,NaN,NaN,191034404,888082482,0000102,39.951128,-75.177119,1900,...,251730.0,27970.0,NaN,NaN,NaN,A,CMX4,2019-11-21,NaN,0.0
488599,7627-31 GERMANTOWN AVE,NaN,NaN,NaN,191183523,871514550,NaN,40.066461,-75.195962,1845,...,218880.0,54720.0,NaN,NaN,F,I,SPPOA,2019-11-20,NaN,10.0
488600,1862 N 27TH ST,NaN,NaN,NaN,191212600,323173400,NaN,39.984365,-75.178421,0,...,0.0,5700.0,NaN,NaN,F,NaN,RSA5,2019-11-22,NaN,0.0
488601,628 SPRING LN,NaN,NaN,NaN,191281046,212408912,NaN,40.067447,-75.245553,1950,...,250750.0,44250.0,NaN,NaN,A,C,RSD3,2019-11-29,NaN,0.0

In [125]:
pluto

,ADDRESS,REIS Submarket,CITY,STATE,ZIP,PARCEL ID,UNIT #,LATITUDE,LONGITUDE,YEAR BUILT,...,BLDG ASSD $,LAND ASSD $,TOT ASSD $,RE TAXES,TOPOGRAPHY,VIEW,ZONING,RECORDING DATE,homestead_exemption,off_street_open
88474,1903 N PHILIP ST,North Frankford,Philadelphia,PA,19122,183286100,NaN,39.979368,-75.137918,1920.0,...,36120.0,32280.0,68400,948,F,I,RM1,6/10/2019,39200.0,0.0
207338,1839-47 BLAIR ST,North Frankford,Philadelphia,PA,19125,888181568,7,39.978068,-75.131378,2017.0,...,80767.0,42700.0,123467,"1,711",F,I,CMX2,6/7/2019,0.0,0.0
404551,1252 PALETHORP ST,North Frankford,Philadelphia,PA,19122,888181894,1,39.970801,-75.138852,2018.0,...,355300.0,62700.0,418000,"5,793",F,I,RM1,6/10/2019,NaN,0.0
128769,620 N 03RD ST,Center City,Philadelphia,PA,19123,888501304,000002C,39.962035,-75.143448,2017.0,...,488400.0,79500.0,567900,"7,870",F,I,NaN,6/3/2019,0.0,0.0
237861,4916 KNORR ST,North Frankford,Philadelphia,PA,19135,412016300,NaN,40.022896,-75.042486,1920.0,...,80862.0,19338.0,100200,"1,389",F,I,RSA5,6/4/2019,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
406990,5450 WHITBY AVE,West Philadelphia,Philadelphia,PA,19143,513156600,NaN,39.944372,-75.230499,1920.0,...,59496.0,10404.0,69900,969,F,I,RM1,4/18/2019,0.0,0.0
413511,901 N PENN ST,Center City,Philadelphia,PA,19123,888061776,000P702,39.961707,-75.134510,2006.0,...,403920.0,55080.0,459000,"6,361",NaN,B,CMX3,6/7/2018,0.0,0.0
428786,4306 TYSON AVE,North Frankford,Philadelphia,PA,19135,552192900,NaN,40.030833,-75.044735,1950.0,...,89980.0,37520.0,127500,"1,767",F,I,RSA3,6/16/2016,40000.0,0.0
446760,1939 CHESTNUT ST,Center City,Philadelphia,PA,19103,888038624,000004A,39.952323,-75.173286,1900.0,...,226000.0,33700.0,259700,"3,599",NaN,I,CMX4,8/8/1991,0.0,0.0
459509,985 N MARSHALL ST,Center City,Philadelphia,PA,19123,141018110,NaN,39.969450,-75.147287,2017.0,...,0.0,73500.0,73500,"1,019",F,I,RM1,NaN,0.0,0.0

In [112]:
columns = pluto_update1.columns.difference(['assessment_date', 'EXT CONDITION DATE'])
pluto_update1[columns][pluto_update1['ADDRESS']=='3227 TEESDALE ST'].values

array([[1.0, 3.0, 0.0, 2.0, 6.0, 1.0, '3227 TEESDALE ST', 'F', 149248.0,
        'Single Family', 'ROW SINGLE FAM', 0.0, 1, 0.0, 'Philadelphia',
        0.0, 0.0, 4.0, 1.0, 'A', 1470.0, 4.0, 26752.0, 0.0, 1754.5,
        40.04094769, -75.04590238, 110.0, 15.95, 176000.0,
        'KEEFE LAUREN             ', nan, nan, nan, 641166400, 'E',
        '2,439', '6/18/2010', 'Torresdale Bensalem', 1.0,
        Timestamp('2019-11-12 00:00:00'), 215000.0, 'PA', 'F', 176000.0,
        1.0, nan, 'I', 1925.0, 19136, 'RSA5 ', 0.0, 0.0]], dtype=object)

In [113]:
pluto_update2[columns][pluto_update2['ADDRESS']=='3227 TEESDALE ST'].values

array([[1.0, 3.0, 0.0, 2.0, 6.0, nan, '3227 TEESDALE ST', 'F', 149248.0,
        'Single Family', 'ROW B/GAR 2 STY MASONRY', 0.0, nan, 'N', nan,
        nan, nan, 4.0, 1.0, 'A', 1470.0, 4.0, 26752.0, 0.0, 1754.5,
        40.040947694247606, -75.04590238171349, 110.0, 15.95, 176000.0,
        'CAI SHUYU                ', '7325 SACKETT ST          ',
        'PHILADELPHIA PA', '19152', 641166400, 'E', nan, '2019-11-14',
        nan, nan, Timestamp('2019-11-12 00:00:00'), 215000.0, nan, 'F',
        nan, nan, nan, 'I', 1925, '191364315', 'RSA5 ', nan, 0.0]],
      dtype=object)

In [110]:
df_sub['EXT CONDITION DATE']

0              NaN
1              NaN
2              NaN
3       2012-07-10
4              NaN
           ...
1188    2012-03-23
1189    2001-03-07
1190           NaN
1191    2012-01-25
1192    2012-05-02
Name: EXT CONDITION DATE, Length: 1193, dtype: object

In [137]:
if not set()-{4}:
    print('yes')

yes